version: 0.2,
phases: 
    install: 
        commands: 
            - npm install
    build: 
        commands: 
            - npm run build
            - npm run cdk synth -- -o
artifacts: 
    type: zip
    files: 
        - template.yml