version: 0.2
phases: 
    install: 
        runtime-versions:
            nodejs: 10
        commands: 
            - apt-get update -y && apt-get install python3-pip
            - pip3 install pipenv --user
            - pipenv install aws-sam-cli
    build:
        commands:
            - pipenv run sam build --use-container
            - pipenv run sam package --s3-bucket cdk-study-bucket --s3-prefix SAMArtifacts --output-template-file sam_output_template.yml
artifacts: 
    type: zip
    files: 
        - sam_output_template.yml