AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cdk-study

  Sample SAM Template for cdk-study

Parameters:
  CognitoUserPoolArn:
    Type: String
  CognitoUserPoolId:
    Type: String

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 90
    Handler: index.handler
    Environment:
      Variables:
        poolId: !Ref CognitoUserPoolId

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: 'CdkRestApi'  
      EndpointConfiguration: EDGE
      Cors:
        AllowHeaders: "'Content-Type, Authorization, Accept'"
        AllowOrigin: "'*'"
        AllowMethods: "'GET, POST, DELETE, PUT, OPTIONS'"
      StageName: prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            AuthType: COGNITO_USER_POOLS
            UserPoolArn: !Ref CognitoUserPoolArn
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
  
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'CdkCreateUserFunction'
      CodeUri: './handlers/CreateUser'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect:
              Resource: '*'
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminAddUserToGroup
                - cognito-idp:AdminUpdateUserAttributes
                - ses:SendEmail
                - mobiletargeting:*
      Events:
        RestApi:
          Type: Api
          Properties:
            Method: POST
            Path: /users/invite
            RestApiId: !Ref RestApi

  

Outputs:
  RestApiUrl:
    Value: !Sub https://n1j9701mf1.execute-api.${AWS::Region}.amazonaws.com/prod/
    Description: API Gateway URL
